import { NextResponse } from 'next/server';

export async function GET() {
  try {
    // Import here to avoid server-side issues
    const { google } = await import('googleapis');
    
    const SHEET_ID = process.env.GOOGLE_SHEETS_SHEET_ID!;
    const PRIVATE_KEY = process.env.GOOGLE_SHEETS_PRIVATE_KEY?.replace(/\\n/g, '\n');
    const CLIENT_EMAIL = process.env.GOOGLE_SHEETS_CLIENT_EMAIL;

    const auth = new google.auth.GoogleAuth({
      credentials: {
        private_key: PRIVATE_KEY,
        client_email: CLIENT_EMAIL,
      },
      scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly'],
    });

    const sheets = google.sheets({ version: 'v4', auth });

    // Get first 5 rows to debug the data structure
    const response = await sheets.spreadsheets.values.get({
      spreadsheetId: SHEET_ID,
      range: 'Generated by Outscraper ©!A1:Q5',
    });

    const rows = response.data.values;

    return NextResponse.json({
      success: true,
      message: 'First 5 rows of sheet data',
      totalColumns: rows?.[0]?.length || 0,
      rows: rows,
      headers: rows?.[0] || [],
      sampleDataRow: rows?.[1] || [],
    });

  } catch (error) {
    console.error('Debug error:', error);
    
    return NextResponse.json({
      success: false,
      error: 'Debug failed',
      message: error instanceof Error ? error.message : 'Unknown error',
    }, { status: 500 });
  }
}